markdown: kramdown
github:
  username: justusdecker
social:
  name: Justus Decker
  links:
    - https://www.linkedin.com/in/justus-decker/
    - https://github.com/justusdecker

title: LPRT - Project